//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Salotto.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Salotto.Resources.AppMessages", typeof(AppMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The account is locked.
        /// </summary>
        public static string Err_AccountLocked {
            get {
                return ResourceManager.GetString("Err_AccountLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A value is needed here.
        /// </summary>
        public static string Err_CantBeEmpty {
            get {
                return ResourceManager.GetString("Err_CantBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event not found.
        /// </summary>
        public static string Err_EventNotFound {
            get {
                return ResourceManager.GetString("Err_EventNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to enter the correct old password and repeat new password twice.
        /// </summary>
        public static string Err_FillAllPasswordFields {
            get {
                return ResourceManager.GetString("Err_FillAllPasswordFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error.
        /// </summary>
        public static string Err_Generic {
            get {
                return ResourceManager.GetString("Err_Generic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image is too big for us.
        /// </summary>
        public static string Err_ImageTooBig {
            get {
                return ResourceManager.GetString("Err_ImageTooBig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to save the photo.
        /// </summary>
        public static string Err_ImgUploadFailed {
            get {
                return ResourceManager.GetString("Err_ImgUploadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We need to know exact user name and password.
        /// </summary>
        public static string Err_IncompleteCredentials {
            get {
                return ResourceManager.GetString("Err_IncompleteCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid credentials.
        /// </summary>
        public static string Err_InvalidCredentials {
            get {
                return ResourceManager.GetString("Err_InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid password.
        /// </summary>
        public static string Err_InvalidPassword {
            get {
                return ResourceManager.GetString("Err_InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max capacity reached.
        /// </summary>
        public static string Err_MaxCapacityReached {
            get {
                return ResourceManager.GetString("Err_MaxCapacityReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation could not be completed successfully.
        /// </summary>
        public static string Err_OperationFailed {
            get {
                return ResourceManager.GetString("Err_OperationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The page is not available.
        /// </summary>
        public static string Err_PageNotAvailable {
            get {
                return ResourceManager.GetString("Err_PageNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords should match!.
        /// </summary>
        public static string Err_PswAreDifferent {
            get {
                return ResourceManager.GetString("Err_PswAreDifferent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation can&apos;t be performed due to security policies..
        /// </summary>
        public static string Err_UnauthorizedOperation {
            get {
                return ResourceManager.GetString("Err_UnauthorizedOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User already exists (change email).
        /// </summary>
        public static string Err_UserAlreadyExists {
            get {
                return ResourceManager.GetString("Err_UserAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found.
        /// </summary>
        public static string Err_UserNotFound {
            get {
                return ResourceManager.GetString("Err_UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a valid email address.
        /// </summary>
        public static string Err_ValidEmailRequired {
            get {
                return ResourceManager.GetString("Err_ValidEmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting.
        /// </summary>
        public static string Info_Connecting {
            get {
                return ResourceManager.GetString("Info_Connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taking longer than expected.
        /// </summary>
        public static string Info_ConnectionIsTakingLonger {
            get {
                return ResourceManager.GetString("Info_ConnectionIsTakingLonger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All done!.
        /// </summary>
        public static string Info_Done {
            get {
                return ResourceManager.GetString("Info_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A confirmation email has been sent to your inbox.
        /// </summary>
        public static string Info_EmailSentToInbox {
            get {
                return ResourceManager.GetString("Info_EmailSentToInbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It just failed!.
        /// </summary>
        public static string Info_Failed {
            get {
                return ResourceManager.GetString("Info_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password has been reset and will be effective on your next access.
        /// </summary>
        public static string Info_PasswordBeenReset {
            get {
                return ResourceManager.GetString("Info_PasswordBeenReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes saved successfully.
        /// </summary>
        public static string Info_SavedChanges {
            get {
                return ResourceManager.GetString("Info_SavedChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure? User will be deleted..
        /// </summary>
        public static string Msg_DeleteConfirm {
            get {
                return ResourceManager.GetString("Msg_DeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation completed successfully.
        /// </summary>
        public static string Success_OperationCompleted {
            get {
                return ResourceManager.GetString("Success_OperationCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password has been changed and will be effective on your next access.
        /// </summary>
        public static string Success_PasswordChanged {
            get {
                return ResourceManager.GetString("Success_PasswordChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run into a network issue .
        /// </summary>
        public static string System_ConnectionError {
            get {
                return ResourceManager.GetString("System_ConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        public static string System_InfoNotAvailable {
            get {
                return ResourceManager.GetString("System_InfoNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not implemented yet.
        /// </summary>
        public static string System_NotImplementedYet {
            get {
                return ResourceManager.GetString("System_NotImplementedYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not specified.
        /// </summary>
        public static string System_NotSpecified {
            get {
                return ResourceManager.GetString("System_NotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops!.
        /// </summary>
        public static string System_Oops {
            get {
                return ResourceManager.GetString("System_Oops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working hard....
        /// </summary>
        public static string System_OperationInProgress {
            get {
                return ResourceManager.GetString("System_OperationInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s not you, but something unexpectedlywent wrong!.
        /// </summary>
        public static string System_SomethingWentWrong {
            get {
                return ResourceManager.GetString("System_SomethingWentWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where would you go from here?.
        /// </summary>
        public static string System_WhereFromHere {
            get {
                return ResourceManager.GetString("System_WhereFromHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password changed.
        /// </summary>
        public static string Text_PasswordChanged {
            get {
                return ResourceManager.GetString("Text_PasswordChanged", resourceCulture);
            }
        }
    }
}
