//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Salotto.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Salotto.Resources.AppStrings", typeof(AppStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email not sent.
        /// </summary>
        public static string EmailNotSent {
            get {
                return ResourceManager.GetString("EmailNotSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string Label_About {
            get {
                return ResourceManager.GetString("Label_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accommodation.
        /// </summary>
        public static string Label_Accommodation {
            get {
                return ResourceManager.GetString("Label_Accommodation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string Label_Account {
            get {
                return ResourceManager.GetString("Label_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Name.
        /// </summary>
        public static string Label_AccountName {
            get {
                return ResourceManager.GetString("Label_AccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accreditation.
        /// </summary>
        public static string Label_Accreditation {
            get {
                return ResourceManager.GetString("Label_Accreditation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accreditation Active.
        /// </summary>
        public static string Label_AccreditationActive {
            get {
                return ResourceManager.GetString("Label_AccreditationActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accreditation Days.
        /// </summary>
        public static string Label_AccreditationDays {
            get {
                return ResourceManager.GetString("Label_AccreditationDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string Label_Actions {
            get {
                return ResourceManager.GetString("Label_Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Label_Address {
            get {
                return ResourceManager.GetString("Label_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Line 1.
        /// </summary>
        public static string Label_Address1 {
            get {
                return ResourceManager.GetString("Label_Address1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address 2.
        /// </summary>
        public static string Label_Address2 {
            get {
                return ResourceManager.GetString("Label_Address2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ATP Uno ID.
        /// </summary>
        public static string Label_AtpUnoId {
            get {
                return ResourceManager.GetString("Label_AtpUnoId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auth By.
        /// </summary>
        public static string Label_AuthBy {
            get {
                return ResourceManager.GetString("Label_AuthBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Badge Role Custom Text.
        /// </summary>
        public static string Label_BadgeRoleCustomText {
            get {
                return ResourceManager.GetString("Label_BadgeRoleCustomText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Badge Role Group.
        /// </summary>
        public static string Label_BadgeRoleGoup {
            get {
                return ResourceManager.GetString("Label_BadgeRoleGoup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Badge role group.
        /// </summary>
        public static string Label_BadgeRoleGroup {
            get {
                return ResourceManager.GetString("Label_BadgeRoleGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Badge Style.
        /// </summary>
        public static string Label_BadgeStyle {
            get {
                return ResourceManager.GetString("Label_BadgeStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Badge Type.
        /// </summary>
        public static string Label_BadgeType {
            get {
                return ResourceManager.GetString("Label_BadgeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BallBoys.
        /// </summary>
        public static string Label_BallBoys {
            get {
                return ResourceManager.GetString("Label_BallBoys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth City.
        /// </summary>
        public static string Label_BirthCity {
            get {
                return ResourceManager.GetString("Label_BirthCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth Country.
        /// </summary>
        public static string Label_BirthCountry {
            get {
                return ResourceManager.GetString("Label_BirthCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth Country Code.
        /// </summary>
        public static string Label_BirthCountryCode {
            get {
                return ResourceManager.GetString("Label_BirthCountryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BirthDate.
        /// </summary>
        public static string Label_BirthDate {
            get {
                return ResourceManager.GetString("Label_BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth Province.
        /// </summary>
        public static string Label_BirthProvince {
            get {
                return ResourceManager.GetString("Label_BirthProvince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blacklist Active.
        /// </summary>
        public static string Label_BlacklistActive {
            get {
                return ResourceManager.GetString("Label_BlacklistActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blacklisted?.
        /// </summary>
        public static string Label_Blacklisted {
            get {
                return ResourceManager.GetString("Label_Blacklisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capacity.
        /// </summary>
        public static string Label_Capacity {
            get {
                return ResourceManager.GetString("Label_Capacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Label_Category {
            get {
                return ResourceManager.GetString("Label_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circuit.
        /// </summary>
        public static string Label_Circuit {
            get {
                return ResourceManager.GetString("Label_Circuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string Label_City {
            get {
                return ResourceManager.GetString("Label_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Label_Code {
            get {
                return ResourceManager.GetString("Label_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string Label_Color {
            get {
                return ResourceManager.GetString("Label_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team.
        /// </summary>
        public static string Label_Company {
            get {
                return ResourceManager.GetString("Label_Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection.
        /// </summary>
        public static string Label_Connection {
            get {
                return ResourceManager.GetString("Label_Connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Group.
        /// </summary>
        public static string Label_ContactGroup {
            get {
                return ResourceManager.GetString("Label_ContactGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Name.
        /// </summary>
        public static string Label_ContactName {
            get {
                return ResourceManager.GetString("Label_ContactName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Source.
        /// </summary>
        public static string Label_ContactSource {
            get {
                return ResourceManager.GetString("Label_ContactSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corinto ID.
        /// </summary>
        public static string Label_CorintoId {
            get {
                return ResourceManager.GetString("Label_CorintoId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Label_Country {
            get {
                return ResourceManager.GetString("Label_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily Accreditation.
        /// </summary>
        public static string Label_DailyAcccreditation {
            get {
                return ResourceManager.GetString("Label_DailyAcccreditation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard.
        /// </summary>
        public static string Label_Default {
            get {
                return ResourceManager.GetString("Label_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Run.
        /// </summary>
        public static string Label_DefaultRun {
            get {
                return ResourceManager.GetString("Label_DefaultRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Label_Description {
            get {
                return ResourceManager.GetString("Label_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Label_Details {
            get {
                return ResourceManager.GetString("Label_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display End Date.
        /// </summary>
        public static string Label_DisplayEndDate {
            get {
                return ResourceManager.GetString("Label_DisplayEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Label_DisplayName {
            get {
                return ResourceManager.GetString("Label_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Start Date.
        /// </summary>
        public static string Label_DisplayStartDate {
            get {
                return ResourceManager.GetString("Label_DisplayStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document.
        /// </summary>
        public static string Label_Document {
            get {
                return ResourceManager.GetString("Label_Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document number.
        /// </summary>
        public static string Label_DocumentNo {
            get {
                return ResourceManager.GetString("Label_DocumentNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document scan.
        /// </summary>
        public static string Label_DocumentScan {
            get {
                return ResourceManager.GetString("Label_DocumentScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document status.
        /// </summary>
        public static string Label_DocumentStatus {
            get {
                return ResourceManager.GetString("Label_DocumentStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document type.
        /// </summary>
        public static string Label_DocumentType {
            get {
                return ResourceManager.GetString("Label_DocumentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Label_Email {
            get {
                return ResourceManager.GetString("Label_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email confirmed.
        /// </summary>
        public static string Label_EmailConfirmed {
            get {
                return ResourceManager.GetString("Label_EmailConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string Label_EndDate {
            get {
                return ResourceManager.GetString("Label_EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax Phone.
        /// </summary>
        public static string Label_FaxPhone {
            get {
                return ResourceManager.GetString("Label_FaxPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string Label_FirstName {
            get {
                return ResourceManager.GetString("Label_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name 2.
        /// </summary>
        public static string Label_FirstName2 {
            get {
                return ResourceManager.GetString("Label_FirstName2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form Password.
        /// </summary>
        public static string Label_FormPassword {
            get {
                return ResourceManager.GetString("Label_FormPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frontend Url.
        /// </summary>
        public static string Label_FrontendUrl {
            get {
                return ResourceManager.GetString("Label_FrontendUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Label_Gender {
            get {
                return ResourceManager.GetString("Label_Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Headshot.
        /// </summary>
        public static string Label_Headshot {
            get {
                return ResourceManager.GetString("Label_Headshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string Label_Id {
            get {
                return ResourceManager.GetString("Label_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Individual account.
        /// </summary>
        public static string Label_Individual {
            get {
                return ResourceManager.GetString("Label_Individual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string Label_Information {
            get {
                return ResourceManager.GetString("Label_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is a player.
        /// </summary>
        public static string Label_IsaPlayer {
            get {
                return ResourceManager.GetString("Label_IsaPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Position.
        /// </summary>
        public static string Label_JobPosition {
            get {
                return ResourceManager.GetString("Label_JobPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JollyField1.
        /// </summary>
        public static string Label_JollyField1 {
            get {
                return ResourceManager.GetString("Label_JollyField1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JollyField2.
        /// </summary>
        public static string Label_JollyField2 {
            get {
                return ResourceManager.GetString("Label_JollyField2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JollyQuestion1.
        /// </summary>
        public static string Label_JollyQuestion1 {
            get {
                return ResourceManager.GetString("Label_JollyQuestion1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JollyQuestion2.
        /// </summary>
        public static string Label_JollyQuestion2 {
            get {
                return ResourceManager.GetString("Label_JollyQuestion2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string Label_LastName {
            get {
                return ResourceManager.GetString("Label_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name 2.
        /// </summary>
        public static string Label_LastName2 {
            get {
                return ResourceManager.GetString("Label_LastName2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last update.
        /// </summary>
        public static string Label_LatestUpdate {
            get {
                return ResourceManager.GetString("Label_LatestUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        public static string Label_Latitude {
            get {
                return ResourceManager.GetString("Label_Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        public static string Label_Line {
            get {
                return ResourceManager.GetString("Label_Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The link is no longer valid.
        /// </summary>
        public static string Label_LinkExpired {
            get {
                return ResourceManager.GetString("Label_LinkExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Label_Location {
            get {
                return ResourceManager.GetString("Label_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked.
        /// </summary>
        public static string Label_Locked {
            get {
                return ResourceManager.GetString("Label_Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LockoutEndDateUtc.
        /// </summary>
        public static string Label_LockoutEndDateUtc {
            get {
                return ResourceManager.GetString("Label_LockoutEndDateUtc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo.
        /// </summary>
        public static string Label_Logo {
            get {
                return ResourceManager.GetString("Label_Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        public static string Label_Longitude {
            get {
                return ResourceManager.GetString("Label_Longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luxor ID.
        /// </summary>
        public static string Label_LuxorId {
            get {
                return ResourceManager.GetString("Label_LuxorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media.
        /// </summary>
        public static string Label_Media {
            get {
                return ResourceManager.GetString("Label_Media", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        public static string Label_Mobile {
            get {
                return ResourceManager.GetString("Label_Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Label_Name {
            get {
                return ResourceManager.GetString("Label_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string Label_NewPassword {
            get {
                return ResourceManager.GetString("Label_NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string Label_Notes {
            get {
                return ResourceManager.GetString("Label_Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not specified.
        /// </summary>
        public static string Label_NotSpecified {
            get {
                return ResourceManager.GetString("Label_NotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of doses.
        /// </summary>
        public static string Label_NumberOfDoses {
            get {
                return ResourceManager.GetString("Label_NumberOfDoses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password.
        /// </summary>
        public static string Label_OldPassword {
            get {
                return ResourceManager.GetString("Label_OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization.
        /// </summary>
        public static string Label_Organization {
            get {
                return ResourceManager.GetString("Label_Organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Label_Password {
            get {
                return ResourceManager.GetString("Label_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password reset.
        /// </summary>
        public static string Label_PasswordReset {
            get {
                return ResourceManager.GetString("Label_PasswordReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions.
        /// </summary>
        public static string Label_Permissions {
            get {
                return ResourceManager.GetString("Label_Permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal.
        /// </summary>
        public static string Label_Personal {
            get {
                return ResourceManager.GetString("Label_Personal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Label_Phone {
            get {
                return ResourceManager.GetString("Label_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone 1.
        /// </summary>
        public static string Label_Phone1 {
            get {
                return ResourceManager.GetString("Label_Phone1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone 2.
        /// </summary>
        public static string Label_Phone2 {
            get {
                return ResourceManager.GetString("Label_Phone2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players Active.
        /// </summary>
        public static string Label_PlayersActive {
            get {
                return ResourceManager.GetString("Label_PlayersActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose.
        /// </summary>
        public static string Label_PleaseChoose {
            get {
                return ResourceManager.GetString("Label_PleaseChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POS Active.
        /// </summary>
        public static string Label_POSActive {
            get {
                return ResourceManager.GetString("Label_POSActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post.
        /// </summary>
        public static string Label_Post {
            get {
                return ResourceManager.GetString("Label_Post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code.
        /// </summary>
        public static string Label_PostalCode {
            get {
                return ResourceManager.GetString("Label_PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefer not to say.
        /// </summary>
        public static string Label_PreferNotToSay {
            get {
                return ResourceManager.GetString("Label_PreferNotToSay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferred Contact Method.
        /// </summary>
        public static string Label_PreferredContactMethod {
            get {
                return ResourceManager.GetString("Label_PreferredContactMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile properties.
        /// </summary>
        public static string Label_ProfileProperties {
            get {
                return ResourceManager.GetString("Label_ProfileProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proof of vaccination.
        /// </summary>
        public static string Label_ProofOfVaccination {
            get {
                return ResourceManager.GetString("Label_ProofOfVaccination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PST Enabled.
        /// </summary>
        public static string Label_PSTEnabled {
            get {
                return ResourceManager.GetString("Label_PSTEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RAW.
        /// </summary>
        public static string Label_RAW {
            get {
                return ResourceManager.GetString("Label_RAW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string Label_Ready {
            get {
                return ResourceManager.GetString("Label_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recover password.
        /// </summary>
        public static string Label_RecoverPassword {
            get {
                return ResourceManager.GetString("Label_RecoverPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ref. Person.
        /// </summary>
        public static string Label_RefPerson {
            get {
                return ResourceManager.GetString("Label_RefPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related accounts.
        /// </summary>
        public static string Label_RelatedAccounts {
            get {
                return ResourceManager.GetString("Label_RelatedAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat password.
        /// </summary>
        public static string Label_RepeatPassword {
            get {
                return ResourceManager.GetString("Label_RepeatPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rfid.
        /// </summary>
        public static string Label_Rfid {
            get {
                return ResourceManager.GetString("Label_Rfid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RM.
        /// </summary>
        public static string Label_RM {
            get {
                return ResourceManager.GetString("Label_RM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string Label_Role {
            get {
                return ResourceManager.GetString("Label_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RPS.
        /// </summary>
        public static string Label_RPS {
            get {
                return ResourceManager.GetString("Label_RPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RS.
        /// </summary>
        public static string Label_RS {
            get {
                return ResourceManager.GetString("Label_RS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Label_Select {
            get {
                return ResourceManager.GetString("Label_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set new password.
        /// </summary>
        public static string Label_SetNewPassword {
            get {
                return ResourceManager.GetString("Label_SetNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string Label_StartDate {
            get {
                return ResourceManager.GetString("Label_StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string Label_State {
            get {
                return ResourceManager.GetString("Label_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Label_Status {
            get {
                return ResourceManager.GetString("Label_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        public static string Label_Test {
            get {
                return ResourceManager.GetString("Label_Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timezone.
        /// </summary>
        public static string Label_Timezone {
            get {
                return ResourceManager.GetString("Label_Timezone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Label_Title {
            get {
                return ResourceManager.GetString("Label_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tournament.
        /// </summary>
        public static string Label_Tournament {
            get {
                return ResourceManager.GetString("Label_Tournament", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transportation.
        /// </summary>
        public static string Label_Transportation {
            get {
                return ResourceManager.GetString("Label_Transportation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Label_Type {
            get {
                return ResourceManager.GetString("Label_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Umpires.
        /// </summary>
        public static string Label_Umpires {
            get {
                return ResourceManager.GetString("Label_Umpires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string Label_Unk {
            get {
                return ResourceManager.GetString("Label_Unk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        public static string Label_URL {
            get {
                return ResourceManager.GetString("Label_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID.
        /// </summary>
        public static string Label_UserId {
            get {
                return ResourceManager.GetString("Label_UserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        public static string Label_UserName {
            get {
                return ResourceManager.GetString("Label_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User properties.
        /// </summary>
        public static string Label_UserProperties {
            get {
                return ResourceManager.GetString("Label_UserProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Seals.
        /// </summary>
        public static string Label_UseSeals {
            get {
                return ResourceManager.GetString("Label_UseSeals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vat.
        /// </summary>
        public static string Label_Vat {
            get {
                return ResourceManager.GetString("Label_Vat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venue.
        /// </summary>
        public static string Label_Venue {
            get {
                return ResourceManager.GetString("Label_Venue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volunteers.
        /// </summary>
        public static string Label_Volunteers {
            get {
                return ResourceManager.GetString("Label_Volunteers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Label_Welcome {
            get {
                return ResourceManager.GetString("Label_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WTA Uno ID.
        /// </summary>
        public static string Label_WtaUnoId {
            get {
                return ResourceManager.GetString("Label_WtaUnoId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string Label_Year {
            get {
                return ResourceManager.GetString("Label_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photos.
        /// </summary>
        public static string Photos {
            get {
                return ResourceManager.GetString("Photos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your new password.
        /// </summary>
        public static string Placeholder_ChangePassword {
            get {
                return ResourceManager.GetString("Placeholder_ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let us know where you wish to receive the link to reset your password.
        /// </summary>
        public static string Placeholder_EmailResetPassword {
            get {
                return ResourceManager.GetString("Placeholder_EmailResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Placeholder_Password {
            get {
                return ResourceManager.GetString("Placeholder_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to She who searches, finds....
        /// </summary>
        public static string Placeholder_SearchFor {
            get {
                return ResourceManager.GetString("Placeholder_SearchFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        public static string Placeholder_UserName {
            get {
                return ResourceManager.GetString("Placeholder_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        public static string System {
            get {
                return ResourceManager.GetString("System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info not available.
        /// </summary>
        public static string System_InfoNotAvailable {
            get {
                return ResourceManager.GetString("System_InfoNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to accounts.
        /// </summary>
        public static string Text_Accounts {
            get {
                return ResourceManager.GetString("Text_Accounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Text_Active {
            get {
                return ResourceManager.GetString("Text_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activities.
        /// </summary>
        public static string Text_Activities {
            get {
                return ResourceManager.GetString("Text_Activities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Info.
        /// </summary>
        public static string Text_AdditionalInfo {
            get {
                return ResourceManager.GetString("Text_AdditionalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New.
        /// </summary>
        public static string Text_AddNew {
            get {
                return ResourceManager.GetString("Text_AddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Information.
        /// </summary>
        public static string Text_AddressInformation {
            get {
                return ResourceManager.GetString("Text_AddressInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin tasks.
        /// </summary>
        public static string Text_AdminTrivia {
            get {
                return ResourceManager.GetString("Text_AdminTrivia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ago.
        /// </summary>
        public static string Text_Ago {
            get {
                return ResourceManager.GetString("Text_Ago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve.
        /// </summary>
        public static string Text_Approve {
            get {
                return ResourceManager.GetString("Text_Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved by.
        /// </summary>
        public static string Text_ApprovedBy {
            get {
                return ResourceManager.GetString("Text_ApprovedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area Overrule.
        /// </summary>
        public static string Text_AreaOverrule {
            get {
                return ResourceManager.GetString("Text_AreaOverrule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to are you trying to &lt;b&gt;delete&lt;/b&gt; this.
        /// </summary>
        public static string Text_AreYouTryingToDeleteThis {
            get {
                return ResourceManager.GetString("Text_AreYouTryingToDeleteThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ATP.
        /// </summary>
        public static string Text_ATP {
            get {
                return ResourceManager.GetString("Text_ATP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Badge Preview.
        /// </summary>
        public static string Text_BadgePreview {
            get {
                return ResourceManager.GetString("Text_BadgePreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Information.
        /// </summary>
        public static string Text_BasicInformation {
            get {
                return ResourceManager.GetString("Text_BasicInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by.
        /// </summary>
        public static string Text_By {
            get {
                return ResourceManager.GetString("Text_By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose an option.
        /// </summary>
        public static string Text_ChooseAnOption {
            get {
                return ResourceManager.GetString("Text_ChooseAnOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to upload.
        /// </summary>
        public static string Text_ClickToUpload {
            get {
                return ResourceManager.GetString("Text_ClickToUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string Text_Comments {
            get {
                return ResourceManager.GetString("Text_Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to team.
        /// </summary>
        public static string Text_Company {
            get {
                return ResourceManager.GetString("Text_Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Groups.
        /// </summary>
        public static string Text_ContactGroups {
            get {
                return ResourceManager.GetString("Text_ContactGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts by source.
        /// </summary>
        public static string Text_ContactsBySource {
            get {
                return ResourceManager.GetString("Text_ContactsBySource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact us.
        /// </summary>
        public static string Text_ContactUs {
            get {
                return ResourceManager.GetString("Text_ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string Text_Continue {
            get {
                return ResourceManager.GetString("Text_Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crafted with.
        /// </summary>
        public static string Text_CraftedWith {
            get {
                return ResourceManager.GetString("Text_CraftedWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Text_Create {
            get {
                return ResourceManager.GetString("Text_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credentials by status.
        /// </summary>
        public static string Text_CredentialsByStatus {
            get {
                return ResourceManager.GetString("Text_CredentialsByStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Run.
        /// </summary>
        public static string Text_CurrentRun {
            get {
                return ResourceManager.GetString("Text_CurrentRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Text_Dashboard {
            get {
                return ResourceManager.GetString("Text_Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to day.
        /// </summary>
        public static string Text_Day {
            get {
                return ResourceManager.GetString("Text_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days.
        /// </summary>
        public static string Text_DayPlural {
            get {
                return ResourceManager.GetString("Text_DayPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Text_Delete {
            get {
                return ResourceManager.GetString("Text_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted.
        /// </summary>
        public static string Text_Deleted {
            get {
                return ResourceManager.GetString("Text_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deny.
        /// </summary>
        public static string Text_Deny {
            get {
                return ResourceManager.GetString("Text_Deny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to developed by Crionet.
        /// </summary>
        public static string Text_DevelopedBy {
            get {
                return ResourceManager.GetString("Text_DevelopedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation.
        /// </summary>
        public static string Text_Documentation {
            get {
                return ResourceManager.GetString("Text_Documentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Text_Edit {
            get {
                return ResourceManager.GetString("Text_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editions.
        /// </summary>
        public static string Text_Editions {
            get {
                return ResourceManager.GetString("Text_Editions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error during the email sending process.
        /// </summary>
        public static string Text_EmailNotSent {
            get {
                return ResourceManager.GetString("Text_EmailNotSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Templates.
        /// </summary>
        public static string Text_EmailTemplates {
            get {
                return ResourceManager.GetString("Text_EmailTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event.
        /// </summary>
        public static string Text_Event {
            get {
                return ResourceManager.GetString("Text_Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        public static string Text_Events {
            get {
                return ResourceManager.GetString("Text_Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events by activity.
        /// </summary>
        public static string Text_EventsByActivity {
            get {
                return ResourceManager.GetString("Text_EventsByActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External Systems Information.
        /// </summary>
        public static string Text_ExternalInformation {
            get {
                return ResourceManager.GetString("Text_ExternalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password?.
        /// </summary>
        public static string Text_ForgotPassword {
            get {
                return ResourceManager.GetString("Text_ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string Text_General {
            get {
                return ResourceManager.GetString("Text_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to credential.
        /// </summary>
        public static string Text_GoToCredential {
            get {
                return ResourceManager.GetString("Text_GoToCredential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi.
        /// </summary>
        public static string Text_Hi {
            get {
                return ResourceManager.GetString("Text_Hi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join.
        /// </summary>
        public static string Text_Join {
            get {
                return ResourceManager.GetString("Text_Join", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo is preferably a landscape image.
        /// </summary>
        public static string Text_LandscapeLogo {
            get {
                return ResourceManager.GetString("Text_LandscapeLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A link has been sent to your email to reset your password.
        /// </summary>
        public static string Text_LinkSent {
            get {
                return ResourceManager.GetString("Text_LinkSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local or external URL.
        /// </summary>
        public static string Text_LocalOrExternalUrl {
            get {
                return ResourceManager.GetString("Text_LocalOrExternalUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Text_Login {
            get {
                return ResourceManager.GetString("Text_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical.
        /// </summary>
        public static string Text_Medical {
            get {
                return ResourceManager.GetString("Text_Medical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        public static string Text_NA {
            get {
                return ResourceManager.GetString("Text_NA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need help?.
        /// </summary>
        public static string Text_NeedHelp {
            get {
                return ResourceManager.GetString("Text_NeedHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string Text_New {
            get {
                return ResourceManager.GetString("Text_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not set.
        /// </summary>
        public static string Text_NotSet {
            get {
                return ResourceManager.GetString("Text_NotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        public static string Text_Pending {
            get {
                return ResourceManager.GetString("Text_Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo.
        /// </summary>
        public static string Text_Photo {
            get {
                return ResourceManager.GetString("Text_Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printed Times.
        /// </summary>
        public static string Text_PrintedTimes {
            get {
                return ResourceManager.GetString("Text_PrintedTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Information.
        /// </summary>
        public static string Text_ProcessInformation {
            get {
                return ResourceManager.GetString("Text_ProcessInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Text_Profile {
            get {
                return ResourceManager.GetString("Text_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public Portal Options.
        /// </summary>
        public static string Text_PublicPortalOptions {
            get {
                return ResourceManager.GetString("Text_PublicPortalOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related Editions.
        /// </summary>
        public static string Text_RelatedEditions {
            get {
                return ResourceManager.GetString("Text_RelatedEditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Text_Remove {
            get {
                return ResourceManager.GetString("Text_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset your password.
        /// </summary>
        public static string Text_ResetYourPassword {
            get {
                return ResourceManager.GetString("Text_ResetYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RFA Last Update on.
        /// </summary>
        public static string Text_RFALastUpdate {
            get {
                return ResourceManager.GetString("Text_RFALastUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RFC Last Update on.
        /// </summary>
        public static string Text_RFCLastUpdate {
            get {
                return ResourceManager.GetString("Text_RFCLastUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RFT Last Update on.
        /// </summary>
        public static string Text_RFTLastUpdate {
            get {
                return ResourceManager.GetString("Text_RFTLastUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string Text_Roles {
            get {
                return ResourceManager.GetString("Text_Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run by country.
        /// </summary>
        public static string Text_RunByCountry {
            get {
                return ResourceManager.GetString("Text_RunByCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runs.
        /// </summary>
        public static string Text_Runs {
            get {
                return ResourceManager.GetString("Text_Runs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Text_Search {
            get {
                return ResourceManager.GetString("Text_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for.
        /// </summary>
        public static string Text_SearchFor {
            get {
                return ResourceManager.GetString("Text_SearchFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Link.
        /// </summary>
        public static string Text_SendLink {
            get {
                return ResourceManager.GetString("Text_SendLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Password.
        /// </summary>
        public static string Text_SetPassword {
            get {
                return ResourceManager.GetString("Text_SetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to set your password.
        /// </summary>
        public static string Text_SetYourPassword {
            get {
                return ResourceManager.GetString("Text_SetYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in to continue to.
        /// </summary>
        public static string Text_SigninToContinue {
            get {
                return ResourceManager.GetString("Text_SigninToContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        public static string Text_Source {
            get {
                return ResourceManager.GetString("Text_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch Run.
        /// </summary>
        public static string Text_SwitchRun {
            get {
                return ResourceManager.GetString("Text_SwitchRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant.
        /// </summary>
        public static string Text_Tenant {
            get {
                return ResourceManager.GetString("Text_Tenant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenants.
        /// </summary>
        public static string Text_Tenants {
            get {
                return ResourceManager.GetString("Text_Tenants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to today.
        /// </summary>
        public static string Text_Today {
            get {
                return ResourceManager.GetString("Text_Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tournaments.
        /// </summary>
        public static string Text_Tournaments {
            get {
                return ResourceManager.GetString("Text_Tournaments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string Text_User {
            get {
                return ResourceManager.GetString("Text_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Text_Users {
            get {
                return ResourceManager.GetString("Text_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View full list.
        /// </summary>
        public static string Text_ViewFullList {
            get {
                return ResourceManager.GetString("Text_ViewFullList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome back to.
        /// </summary>
        public static string Text_WelcomeBack {
            get {
                return ResourceManager.GetString("Text_WelcomeBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WTA.
        /// </summary>
        public static string Text_WTA {
            get {
                return ResourceManager.GetString("Text_WTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yesterday.
        /// </summary>
        public static string Text_Yesterday {
            get {
                return ResourceManager.GetString("Text_Yesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending posts.
        /// </summary>
        public static string Title_PendingPosts {
            get {
                return ResourceManager.GetString("Title_PendingPosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users By Role.
        /// </summary>
        public static string UsersByRole {
            get {
                return ResourceManager.GetString("UsersByRole", resourceCulture);
            }
        }
    }
}
